export const simpleIconsSlugs: Record<string, string> = {
  'Node.js': 'siNodedotjs',
  Angular: 'siAngular',
  TypeScript: 'siTypescript',
  CSS: 'siCss',
  HTML: 'siHtml5',
  JavaScript: 'siJavascript',
  Karma: 'siJasmine',
  Jest: 'siJest',
  Git: 'siGit',
  Gist: 'siGit',
  'Express.js': 'siExpress',
  MongoDB: 'siMongodb',
  Mongoose: 'siMongoose',
  'Nest.js': 'siNestjs',
  RxJS: 'siReactivex',
  React: 'siReact',
  'React Native': 'siReact',
  Ionic: 'siIonic',
  'Next.js': 'siNextdotjs',
  MySQL: 'siMysql',
  WordPress: 'siWordpress',
  Figma: 'siFigma',
};
